version: "3.8"

services:
  your_service_name:
    build: .
    environment:
      - OPENAI_API_KEY=your_openai_api_key_here
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: unless-stopped